title: Mike Tannenbaum | Design Strategist
author: miketannenbaum
include: ['_pages']

permalink:           pretty
relative_permalinks: false

plugins:
  - jekyll-last-modified-at
  - jekyll-feed
  - jekyll-twitter-plugin
  - jekyll-seo-tag
  - jekyll-spaceship
  - jekyll_picture_tag
sass:
  sass_dir:          _sass
  style:            :compressed

collections:
  notes:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
